-- MySQL Script generated by MySQL Workbench
-- Mon May 28 17:02:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`membre` (
  `id_membre` INT(3) NOT NULL DEFAULT 000,
  `pseudo` VARCHAR(20) NULL,
  `mdp` VARCHAR(60) NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(20) NULL,
  `email` VARCHAR(50) NULL,
  `civilite` VARCHAR(45) NULL,
  `ville` VARCHAR(20) NULL,
  `code_postal` INT(3) NULL,
  `adresse` VARCHAR(50) NULL,
  `statut` INT(1) NULL,
  PRIMARY KEY (`id_membre`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`produit` (
  `id_produit` INT(3) NOT NULL DEFAULT 000,
  `reference` VARCHAR(20) NULL,
  `categorie` VARCHAR(20) NULL,
  `titre` VARCHAR(100) NULL,
  `description` LONGTEXT NULL,
  `couleur` VARCHAR(20) NULL,
  `taille` VARCHAR(5) NULL,
  `public` VARCHAR(45) NULL,
  `photo` VARCHAR(250) NULL,
  `prix` INT(3) NULL,
  `stock` INT(3) NULL,
  PRIMARY KEY (`id_produit`),
  UNIQUE INDEX `reference_UNIQUE` (`reference` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`commande` (
  `id_commande` INT(3) UNSIGNED NOT NULL DEFAULT 000,
  `montant` INT(3) NULL,
  `date_enregistrement` DATETIME NULL,
  `etat` VARCHAR(45) NULL,
  `id_membre` INT(3) NOT NULL,
  PRIMARY KEY (`id_commande`, `id_membre`),
  INDEX `fk_commande_membre_idx` (`id_membre` ASC),
  CONSTRAINT `fk_commande_membre`
    FOREIGN KEY (`id_membre`)
    REFERENCES `ecommerce`.`membre` (`id_membre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`details_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`details_commande` (
  `id_details_commande` INT(3) UNSIGNED NOT NULL DEFAULT 000,
  `quantite` INT(3) NULL,
  `prix` INT(3) NULL,
  `details_commande` VARCHAR(45) NULL,
  `id_produit` INT(3) NOT NULL,
  `id_commande` INT(3) UNSIGNED NOT NULL,
  `commande_id_membre` INT(3) NOT NULL,
  PRIMARY KEY (`id_details_commande`, `id_produit`, `id_commande`, `commande_id_membre`),
  INDEX `fk_details_commande_produit1_idx` (`id_produit` ASC),
  INDEX `fk_details_commande_commande1_idx` (`id_commande` ASC, `commande_id_membre` ASC),
  CONSTRAINT `fk_details_commande_produit1`
    FOREIGN KEY (`id_produit`)
    REFERENCES `ecommerce`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_details_commande_commande1`
    FOREIGN KEY (`id_commande` , `commande_id_membre`)
    REFERENCES `ecommerce`.`commande` (`id_commande` , `id_membre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
